name: exe12
description: Exemplo com dois imports usando aliases
version: 1.0.0
environment:
  sdk: ">=2.19.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
